name: iavl-ut 

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  iavl:
    name: iavl tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test & coverage report creation
        run: |
          go test ./libs/iavl/...
