name: tendermint-ut

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - uses: actions/setup-go@v2
      - name: Set GOBIN
        run: |
          echo "GOBIN=$(go env GOPATH)/bin" >> $GITHUB_ENV
      - uses: actions/checkout@v2.3.4
      - name: install
        run: cd ./libs/tendermint && make install install_abci && cd -
      # Cache bin
      - uses: actions/cache@v1
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-tm-binary

  tm-core:
    name: tm-core tests
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: test_tm_core
        continue-on-error: true
        run: |
          go test -count=1 ./libs/tendermint/libs/async/...
          go test -count=1 ./libs/tendermint/lite/...
          go test -count=1 ./libs/tendermint/mempool/...
          go test -count=1 ./libs/tendermint/consensus/...

  test_abci_apps:
    name: abci_apps tests
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/setup-go@v2
      - name: Set GOBIN
        run: |
          echo "GOBIN=$(go env GOPATH)/bin" >> $GITHUB_ENV
      - uses: actions/checkout@v2.3.4
      - uses: actions/cache@v1
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-tm-binary
      - name: test_abci_apps
        run: ./libs/tendermint/abci/tests/test_app/test.sh
        shell: bash

  test_abci_cli:
    name: abci_cli tests
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/setup-go@v2
      - name: Set GOBIN
        run: |
          echo "GOBIN=$(go env GOPATH)/bin" >> $GITHUB_ENV
      - uses: actions/checkout@v2.3.4
      - uses: actions/cache@v1
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-tm-binary
      - run: ./libs/tendermint/abci/tests/test_cli/test.sh
        shell: bash
